name: Build Docker image and scan with Grype
on:
  workflow_dispatch
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Build image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: dockerfile
        tags: uvicorn/uvicorn:latest

    - name: Scan with Grype
      run: |
         curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
         grype uvicorn/uvicorn:latest -o table

    - name: Scan with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: uvicorn/uvicorn:latest
