name: Build Echo Docker image and scan with Grype
on:
  workflow_dispatch
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Log in to Docker registry
      uses: docker/login-action@v3
      with:
        registry: reg.echohq.com
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: dockerfile-echo
        tags: uvicorn/uvicorn-echo:latest

    - name: Install Grype
      run: curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Scan the Docker image
      run: grype uvicorn/uvicorn-echo:latest -o table
