name: Build Echo Docker image and scan with Grype
on:
  workflow_dispatch
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Log in to Docker registry
      uses: docker/login-action@v3
      with:
        registry: reg.echohq.com
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: dockerfile-echo
        tags: uvicorn/uvicorn-echo:latest

    - name: Scan the Docker image
      id: scan
      uses: anchore/scan-action@v3
      with:
        image: uvicorn/uvicorn-echo:latest
        update-db: true
        fail-build: false
        output-format: table
